server:
  port: 8080

spring:
  application:
    name: accounts
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  profiles:
    active: prod

  config:
    import: "optional:configserver:http://localhost:8071/"
#   optional:configserver:http;//localhost:8071/ -optional when the profile is not too important

management:
  endpoints:
    web:
      exposure:
        include: "*"




